### PR TITLE
Jruby: more compatibility

### PR DESCRIPTION
**Pull request by funny-falcon**
just more compatibility

### CODE REVIEW

**Comment by tagomoris** [comment]
Almost diff seems reasonable and good to merge.
But about `TypeError`, I'll merge #86 to use `MessagePack::UnexpectedTypeError`.
Could you follow that change, and rebase on master?

**Comment by funny-falcon** [comment]
No problem. Just remind me when to rebase on master.

**Comment by tagomoris** [comment]
OK for now. #86 has some change for exceptions, and merged.
I hope that you will fix your changes to follow #86 changes.

**Comment by funny-falcon** [comment]
done + ExtensionValue compatibility.

**Comment by tagomoris** [comment]
Great patch to improve jruby implementation. Thank you!

**Pull request merged**
