### PR TITLE
Fix code indent with 4 spaces for each levels

### PR DESCRIPTION
**Pull request by tagomoris**
There's some indentation rules for java code:
* Sun's code convensions: 2 spaces
 * http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html
* Maven coding style: 4 spaces
 * https://maven.apache.org/developers/conventions/code.html
* Eclipse Coding Convention: tab (4 space wide)
 * https://wiki.eclipse.org/Coding_Conventions
* Google style guide: 2 spaces (4 spaces for continuation lines)
 * https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent
* JRuby Style Guide (Java code): 4 spaces
 * https://github.com/jruby/jruby/wiki/JRubyStyleGuide

I think we should follow JRuby Style Guide.

### CODE REVIEW

**Comment by iconara** [comment]
Why? Really, why?

This is so unnecessary and will make all git history meaningless. Please don't do this.

**Comment by tagomoris** [comment]
In sight of git, we can use `-w` option to ignore whitespace differences. Isn't it enough for you?
I always fix my code indent manually for 2-space JRuby Java code...

**Comment by iconara** [comment]
I'm going to stop contributing to this project if you're going ahead with this. It's so irresponsible and unnecessary.

**Comment by iconara** [comment]
I don't care about what guideline a piece of code follows. That's unimportant. I always follow the style of the existing code, I try to adapt to the project. I don't impose my style on others, I try to collaborate. I don't feel that this is in that spirit.

**Comment by tagomoris** [comment]
I see. I'll decline this change.

**Pull request closed without merging**
