### PR TITLE
Visual C++ support.

### PR DESCRIPTION
**Pull request by unak**
* ext/msgpack/sysdep_types.h (bool): Visual C++ in C mode does not have bool.
  define it just like the C99 way.

* others: narrow scoping is a good practice.  but suddly Visual C++ in C mode
  does not support declaring variables except the top of functions.

### CODE REVIEW

**Comment by tagomoris** [comment]
What can i do for this?

**Comment by nurse** [comment]
Considered this thread is already done.

**Comment by cosmo0920** [comment]
Visual Studio 2013 has `_Bool` type (also we can write it as `bool` with including stdbool.h).
Perhaps, Visual Studio 2015 solves C99 issue totally.

**Comment by tagomoris** [comment]
I'll close this at once. Please open another issues if there are any additional problems with recent environment.

**Pull request closed without merging**
