### PR TITLE
Extended type support

### PR DESCRIPTION
**Pull request by ramonmaruko**
My C is not really good, so please review this properly. Thank you.

### CODE REVIEW

**Comment by ramonmaruko** [comment]
Sorry if it took me too long to implement `::register_extension`. I was busy with other things.

**Comment by sardaukar** [comment]
Great work, thanks!

**Comment by tagomoris** [comment]
My review results are:
* ext type information should be for packer/unpacker instances, not runtime global

Now we should consider about JRuby implementation...

**Comment by ramonmaruko** [comment]
Seems like this isn't needed anymore since #71 is already here.

**Pull request closed without merging**
