### PR TITLE
Enable GitHub Actions

### PR DESCRIPTION
**Pull request by tagomoris**
The change is originally provided by #203

### CODE REVIEW

**Comment by tagomoris** [comment]
The current workflow looks working well. I fixed the workflow for TruffleRuby to succeed always even when tests fail.
@casperisfine Thank you for the base config!

**Comment by tagomoris** [comment]
Ah, and @byroot !

**Comment by casperisfine** [comment]
> @casperisfine Thank you for the base config!

You're welcome!

> Ah, and @byroot !

We're the same person 😉

**Comment by tagomoris** [comment]
> We're the same person 😉
I saw only the account name. Sorry!

**Pull request merged**
