### PR TITLE
Fix test suite on platforms without compaction support

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: #354

### CODE REVIEW

**Review by byroot — APPROVED** [review]

**Comment by matoro** [comment]
Hi, I noted in https://github.com/msgpack/msgpack-ruby/issues/354 that this seemed the obvious fix to me and so I had already tried it, but this commit causes the test suite to hang.  Output is just:

```
buffer_io random seed: 0x6bcdeddedff9306664eb005489b573d6
buffer random seed: 0x7c581d44e0ab7455e52e90c9ce3a4d82
```

and then it spins chewing one CPU core.

**Comment by matoro** [comment]
> If you remove the `auto_compact = true` call entirely, does it work?
> 
> If so I'm happy to take a PR that detect your environment and just skips this part.

Hmmm, no it still hangs, so this must not be the cause.  I provide [free shell access](https://static.matoro.tk/isa-sandbox-faq.html) to all of the machines I use to reproduce these bugs on, would this be useful to look into it?

**Comment by casperisfine** [comment]
> would this be useful to look into it?

I might if I have time to kill.

In the meantime, what happens if you send a SEGV signal? That should trigger the ruby crash report and give you a C-backtrace of where ruby is hanging.

**Comment by byroot** [comment]
Thanks, ok so this is very weird. It's literally stuck loading the code, it hasn't even started the test suite yet.

I really have little idea what it could be.

**Comment by matoro** [comment]
Recompiled everything with -O0, debug assertions, etc.  Slightly better backtrace here - the exact line varies slightly depending on when I stop it, but everything up to the top 2 frames or so is consistent.

```
0x00007ffff7932a24 in heap_next_freepage (objspace=0x1000340e0, size_pool=0x100034108, heap=0x100034118) at gc.c:2392                                                                                                                            
2392        while (heap->free_pages == NULL) {                                                                                                                                                                                                   
(gdb) bt                                                                                                                                                                                                                                         
#0  0x00007ffff7932a24 in heap_next_freepage (objspace=0x1000340e0, size_pool=0x100034108, heap=0x100034118) at gc.c:2392                                                                                                                        
#1  0x00007ffff7932ba4 in ractor_cache_slots (objspace=0x1000340e0, cr=0x100034ed0, size_pool_idx=0) at gc.c:2429                                                                                                                                
#2  0x00007ffff7932ddc in newobj_slowpath (size_pool_idx=0, wb_protected=1, cr=0x100034ed0, objspace=0x1000340e0, flags=5, klass=4295926840) at gc.c:2489                                                                                        
#3  newobj_slowpath_wb_protected (klass=4295926840, flags=5, objspace=0x1000340e0, cr=0x100034ed0, size_pool_idx=0) at gc.c:2509                                                                                                                 
#4  0x00007ffff793327c in newobj_of0 (klass=4295926840, flags=5, wb_protected=1, cr=0x100034ed0, alloc_size=32) at gc.c:2550                                                                                                                     
#5  0x00007ffff7933330 in newobj_of (klass=4295926840, flags=5, v1=0, v2=0, v3=0, wb_protected=1, alloc_size=32) at gc.c:2560                                                                                                                    
#6  0x00007ffff79334c0 in rb_wb_protected_newobj_of (klass=4295926840, flags=5, size=32) at gc.c:2582                                                                                                                                            
#7  0x00007ffff7ae3d54 in str_alloc (klass=4295926840, size=32) at string.c:845                                                                                                                                                                  
#8  0x00007ffff7ae3dc8 in str_alloc_embed (klass=4295926840, capa=16) at string.c:858                                                                                                                                                            
#9  0x00007ffff7ae3f98 in str_new0 (klass=4295926840, ptr=0x100cb4860 "symbolized keys", len=15, termlen=1) at string.c:888                                                                                                                      
#10 0x00007ffff7ae43cc in rb_enc_str_new (ptr=0x100cb4860 "symbolized keys", len=15, enc=0x100037d60) at string.c:946                                                                                                                            
#11 0x00007ffff7a0f0b4 in parser_str_new (ptr=0x100cb4860 "symbolized keys", len=15, enc=0x100037d60, func=64, enc0=0x100037d60) at parse.y:6563                                                                                                 
#12 0x00007ffff7a12480 in parse_string (p=0x100cade80, quote=0x100048168) at parse.y:7523
#13 0x00007ffff7a18d94 in parser_yylex (p=0x100cade80) at parse.y:9268
#14 0x00007ffff7a1b8e8 in yylex (lval=0x7fffffff81e8, yylloc=0x7fffffff8360, p=0x100cade80) at parse.y:9971
#15 0x00007ffff7a00590 in ruby_yyparse (p=0x100cade80) at parse.c:7037
#16 0x00007ffff7a0e564 in yycompile0 (arg=4308262528) at parse.y:6357
#17 0x00007ffff7bc4e1c in rb_suppress_tracing (func=0x7ffff7a0e3b0 <yycompile0>, arg=4308262528) at vm_trace.c:463
#18 0x00007ffff7a0e8d8 in yycompile (vparser=4298150120, p=0x100cade80, fname=4298150200, line=1) at parse.y:6408
#19 0x00007ffff7a0eeec in rb_parser_compile_file_path (vparser=4298150120, fname=4298150200, file=4298149720, start=1) at parse.y:6511
#20 0x00007ffff7ac09cc in load_file_internal (argp_v=140737488331424) at ruby.c:2368
#21 0x00007ffff7917804 in rb_ensure (b_proc=0x7ffff7ac030c <load_file_internal>, data1=140737488331424, e_proc=0x7ffff7ac0e04 <restore_load_file>, data2=140737488331424) at eval.c:997
#22 0x00007ffff7ac0f2c in load_file (parser=4298150120, fname=4298150200, f=4298149720, script=0, opt=0x7fffffffa320) at ruby.c:2503
#23 0x00007ffff7ac10a8 in rb_parser_load_file (parser=4298150120, fname_v=4298150200) at ruby.c:2525
#24 0x00007ffff79b4fe0 in load_iseq_eval (ec=0x100034880, fname=4298150200) at load.c:654
#25 0x00007ffff79b5398 in rb_load_internal (fname=4298150200, wrap=8) at load.c:721
#26 0x00007ffff79b56f0 in rb_f_load (argc=1, argv=0x7ffff72f0200, _=4300223280) at load.c:796
#27 0x00007ffff7b860e8 in ractor_safe_call_cfunc_m1 (recv=4300223280, argc=1, argv=0x7ffff72f0200, func=0x7ffff79b55fc <rb_f_load>) at vm_insnhelper.c:2847
#28 0x00007ffff7b8734c in vm_call_cfunc_with_frame (ec=0x100034880, reg_cfp=0x7ffff73efd10, calling=0x7fffffffabc0) at vm_insnhelper.c:3037
#29 0x00007ffff7b8753c in vm_call_cfunc (ec=0x100034880, reg_cfp=0x7ffff73efd10, calling=0x7fffffffabc0) at vm_insnhelper.c:3058
#30 0x00007ffff7b89b18 in vm_call_method_each_type (ec=0x100034880, cfp=0x7ffff73efd10, calling=0x7fffffffabc0) at vm_insnhelper.c:3639
#31 0x00007ffff7b8a310 in vm_call_method (ec=0x100034880, cfp=0x7ffff73efd10, calling=0x7fffffffabc0) at vm_insnhelper.c:3736
#32 0x00007ffff7b88670 in vm_call_symbol (ec=0x100034880, reg_cfp=0x7ffff73efd10, calling=0x7fffffffabc0, ci=0xc0100140005, symbol=5681420) at vm_insnhelper.c:3263
#33 0x00007ffff7b88818 in vm_call_opt_send (ec=0x100034880, reg_cfp=0x7ffff73efd10, calling=0x7fffffffabc0) at vm_insnhelper.c:3303
#34 0x00007ffff7b8d50c in vm_sendish (ec=0x100034880, reg_cfp=0x7ffff73efd10, cd=0x1005bbba0, block_handler=0, method_explorer=mexp_search_method) at vm_insnhelper.c:4751
#35 0x00007ffff7b959c4 in vm_exec_core (ec=0x100034880, initial=0) at insns.def:778
#36 0x00007ffff7bb1948 in rb_vm_exec (ec=0x100034880, mjit_enable_p=true) at vm.c:2211
#37 0x00007ffff7badf10 in invoke_block (ec=0x100034880, iseq=0x100490290, self=4300223280, captured=0x7ffff73efde8, cref=0x0, type=572653569, opt_pc=0) at vm.c:1316
#38 0x00007ffff7bae2cc in invoke_iseq_block_from_c (me=0x0, is_lambda=0, cref=0x0, passed_block_handler=0, kw_splat=0, argv=0x7fffffffbf88, argc=1, self=4300223280, captured=0x7ffff73efde8, ec=0x100034880) at vm.c:1372
#39 invoke_block_from_c_bh (ec=0x100034880, block_handler=140737341488617, argc=1, argv=0x7fffffffbf88, kw_splat=0, passed_block_handler=0, cref=0x0, is_lambda=0, force_blockarg=0) at vm.c:1390
#40 0x00007ffff7bae4ec in vm_yield_with_cref (ec=0x100034880, argc=1, argv=0x7fffffffbf88, kw_splat=0, cref=0x0, is_lambda=0) at vm.c:1427
#41 0x00007ffff7bae570 in vm_yield (ec=0x100034880, argc=1, argv=0x7fffffffbf88, kw_splat=0) at vm.c:1435
#42 0x00007ffff7ba75b4 in rb_yield_0 (argc=1, argv=0x7fffffffbf88) at vm_eval.c:1347
#43 0x00007ffff7ba7684 in rb_yield (val=4301766320) at vm_eval.c:1363
#44 0x00007ffff784c130 in rb_ary_each (ary=4301763600) at array.c:2522
#45 0x00007ffff7b86164 in ractor_safe_call_cfunc_0 (recv=4301763600, argc=0, argv=0x7ffff72f0170, func=0x7ffff784c094 <rb_ary_each>) at vm_insnhelper.c:2854
#46 0x00007ffff7b8734c in vm_call_cfunc_with_frame (ec=0x100034880, reg_cfp=0x7ffff73efdd0, calling=0x7fffffffc230) at vm_insnhelper.c:3037
#47 0x00007ffff7b8d50c in vm_sendish (ec=0x100034880, reg_cfp=0x7ffff73efdd0, cd=0x100459770, block_handler=140737341488617, method_explorer=mexp_search_method) at vm_insnhelper.c:4751
#48 0x00007ffff7b9587c in vm_exec_core (ec=0x100034880, initial=0) at insns.def:759
#49 0x00007ffff7bb198c in rb_vm_exec (ec=0x100034880, mjit_enable_p=true) at vm.c:2220
#50 0x00007ffff7bb25e0 in rb_iseq_eval (iseq=0x100369ee8) at vm.c:2458
#51 0x00007ffff79b5064 in load_iseq_eval (ec=0x100034880, fname=4298547840) at load.c:660
#52 0x00007ffff79b5398 in rb_load_internal (fname=4298547840, wrap=8) at load.c:721
#53 0x00007ffff79b56f0 in rb_f_load (argc=1, argv=0x7ffff72f0048, _=4295951080) at load.c:796
#54 0x00007ffff7b860e8 in ractor_safe_call_cfunc_m1 (recv=4295951080, argc=1, argv=0x7ffff72f0048, func=0x7ffff79b55fc <rb_f_load>) at vm_insnhelper.c:2847
#55 0x00007ffff7b8734c in vm_call_cfunc_with_frame (ec=0x100034880, reg_cfp=0x7ffff73eff90, calling=0x7fffffffd9f0) at vm_insnhelper.c:3037
#56 0x00007ffff7b8753c in vm_call_cfunc (ec=0x100034880, reg_cfp=0x7ffff73eff90, calling=0x7fffffffd9f0) at vm_insnhelper.c:3058
#57 0x00007ffff7b89b18 in vm_call_method_each_type (ec=0x100034880, cfp=0x7ffff73eff90, calling=0x7fffffffd9f0) at vm_insnhelper.c:3639
#58 0x00007ffff7b8a310 in vm_call_method (ec=0x100034880, cfp=0x7ffff73eff90, calling=0x7fffffffd9f0) at vm_insnhelper.c:3736
#59 0x00007ffff7b8a4cc in vm_call_general (ec=0x100034880, reg_cfp=0x7ffff73eff90, calling=0x7fffffffd9f0) at vm_insnhelper.c:3768
#60 0x00007ffff7b8d50c in vm_sendish (ec=0x100034880, reg_cfp=0x7ffff73eff90, cd=0x10017ee60, block_handler=0, method_explorer=mexp_search_method) at vm_insnhelper.c:4751
#61 0x00007ffff7b959c4 in vm_exec_core (ec=0x100034880, initial=0) at insns.def:778
#62 0x00007ffff7bb198c in rb_vm_exec (ec=0x100034880, mjit_enable_p=true) at vm.c:2220
#63 0x00007ffff7bb2654 in rb_iseq_eval_main (iseq=0x100337d80) at vm.c:2469
#64 0x00007ffff7915590 in rb_ec_exec_node (ec=0x100034880, n=0x100337d80) at eval.c:280
#65 0x00007ffff7915798 in ruby_run_node (n=0x100337d80) at eval.c:321
#66 0x0000000100000bdc in main (argc=4, argv=0x7ffffffff328) at ./main.c:47
```

**Comment by matoro** [comment]
Well...interesting discovery, everything works on Ruby 3.2!

**Comment by casperisfine** [comment]
Interesting backtrace. I wonder if somehow it's a Ruby 3.1 GC bug (e.g. `hile (heap->free_pages == NULL) {  ` ending up in an infinite loop or something).

@peterzhu2118 does that ring any bell?

But good news on 3.2 working!

**Pull request merged**
