### PR TITLE
Add RBX-3 to the build

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by tagomoris** [comment]
We don't support Rubinius explicitly anymore.

**Comment by thedrow** [comment]
That's a shame.

**Comment by chuckremes** [comment]
@tagomoris If this is due to Rubinius builds failing on travis-ci regularly, we have gotten that mostly under control. If we can promise to keep the Rubinius travis-ci release builds more reliable will you consider re-adding Rubinius to the test matrix? cc/ @brixen

**Comment by tagomoris** [comment]
It might be, or not. Supporting Rubinius requires much more `ifdef` in our *.c code, but there are not maintainer about Rubinius environment of this library. I (and original author) don't use this on Rubinius, but there are many times to take some additional time to support Rubinius after writing code perfectly working on CRuby.

Are there any users of this library on Rubinius environment?

**Comment by thedrow** [comment]
We're currently evaluating RBX where I work and we need it to be supported since msgpack is one of our dependencies.

**Comment by tagomoris** [comment]
Interesting. Can you join to maintaining this project for Rubinius?
(It means that can you create a pull-request to remove needless `ifdef`s for latest Rubinius?)

**Comment by brixen** [comment]
To enable Rubinius in Travis builds, 'rbx' should be used. This avoids bugs in RVM and will run the tests on the latest Rubinius 3.x release.

If Travis build issues on Rubinius are a problem, Travis provides `allow_failures` [as described in the documentation](https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail).

Finally, [mochilo](https://github.com/brianmario/mochilo) provides a superset of MsgPack and the build passes on Rubinius https://travis-ci.org/rubinius/mochilo/builds/139250350.

**Comment by chuckremes** [comment]
@tagomoris Sure, I'll happily join the project as a collaborator to handle Rubinius items. Go ahead and add me.

**Comment by tagomoris** [comment]
@chuckremes I'll add you after you created a pull-request to update code for rbx3.

**Pull request closed without merging**
